### ISSUE TITLE
Add setup instructions

### ISSUE THREAD

**Issue by briantopping** [pferrel/3-input-cooc#1]
Thanks for sharing your project here. Looks like you had intended to give instructions for setting up SBT, but they are dead links. I noticed that there's a dependency on the sbt-pack plugin but I didn't have it set up. 

For others running into this, create a `~/.sbt/0.13/plugins/build.sbt` and create a two line file with `addSbtPlugin("org.xerial.sbt" % "sbt-pack" % "0.6.8")` as the first line and a blank line or three to please the capricious SBT gods. Your build should work thereafter.

**EDIT:** I also noticed that the setup of Mahout and Spark are assumed. Since this project is referenced from the Mahout site, it would be helpful for those getting started to make sure they know how to do this, for instance with Macports and Homebrew on OS X, but more importantly, if those methods are not sufficient in some way.

**Comment by pferrel** [comment]
Thanks, a work in progress--the .mscala version needs work too.

The SBT gods are indeed capricious. Installing SBT 0.13 + should get the build going, no need for the changes above afaik. @briantopping can you pull the latest, undo your changes, make sure you have the 0.13.x version of SBT and try again? Hard for me to say for sure since I've used it in previous projects and it may be resolved from some hidden cache.

@briantopping this is a tutorial on the Apache Mahout site here: http://mahout.apache.org/users/environment/how-to-build-an-app.html

**Comment by briantopping** [comment]
Hi Patrick, could you first do a `grep -R` on your ~/.sbt for any occurrences of "sbt-pack"? That should find if you have any hidden copies of the `addSbtPlugin` that we care about here. I actually found this project through the link you have here, really appreciate your work on it.

As it turns out, Mahout is available as a Macports package, but Spark is not available that way. I was working on that next and got distracted in the lazy hot afternoon.

**Comment by pferrel** [comment]
Yeah, I looked there and only have the pom reader plugin. Grep is empty

The setup was expanded a bit to point out the setup of Spark and Mahout. You grabbed this as I was working on it, really appreciate you trying it out.

**Comment by briantopping** [comment]
Great timing for both of us, really. Thanks to you!

I'll check out the changes after some sleep. More as I get it! :)

**Comment by pferrel** [comment]
Sleep=good

Added a section for using the debugger. Light on instructions about adding the Scala plugin to IntelliJ IDEA so hopefully that's not too hard.

Also added how to run this in the Mahout REPL shell that extends Spark's shell.

happy to hear any suggestions, and thanks

**Comment by phiripatrick663** [comment]
Hi Patrick,
I am learning recommenders and have followed your extensive work in this area. Thank you. I do agree with Brian that there are scant setup instructions, and to someone new like me its a daunting task. 

I have tried to setup the project in IntelliJ but am getting an error; "No jdk for module 3-input-cooc-master". Not sure if this means no java path set for the project, but I do have jdk1.7.0_51 setup and its in use with no issues.

Thanks.
Patrick

**Comment by pferrel** [comment]
You need to tell IntelliJ where your JDK is so it knows what to use. Go to "Project structure" --> "Project Settings" --> "Project" and choose the Java 1.7 or 1.8 JDK in the dropdown or create a new one and find it in the filesystem. This will be required even before doing thing listed below.

You might find it much easier to use the new Universal Recommender Template for Predicition.io here: https://github.com/PredictionIO/template-scala-parallel-universal-recommendation

PIO has all the components to make the recommender work as a REST endpoint for recommendations queries and has an EventServer to send training events to. Also several SDKs are available so apps can send events and make queries.

Try the one-line install of the PIO Framework then install and build the Template.
I support the Template on the Prediction.io Google group or through issues logged against the Template.

**Comment by phiripatrick663** [comment]
Thanks for the quick response. I noticed that I had missed one important detail, I had not added Scala plugin. Doing that now and will check the java setup. Will post update in a bit.

Thanks for the link to the universal recommender, will definitely check it out. I must say though, I have faced a few sbt issues, corrupt launch jar file, trying to build Spark that I have yet to resolve.

Thanks.

**Comment by pferrel** [comment]
The installation of the pio framework comes with instructions for setting up IntelliJ with the Scala plugin and Java 7 or 8 (though it is harder to use with PIO than this sample project) It also installs sbt along with Spark and the rest of the needed components and comes with a more active community for support. 

If you want to roll your own integration of Mahout cooccurrence and all the components necessary you can certainly do that too but will be dealing with an unending supply of these issues--all considered the price of "free", I guess. I've been where you are and lived through it but you have to be persistent. For instance, when writing any docs I assumed one would know to install the Scala plugin to debug Scala but this may not be so obvious to someone new to the project, sorry.

**Comment by phiripatrick663** [comment]
Yes, thanks for the pointers. I will go with the project as is, so I can develop a better understanding of how the tools are applied before venturing to some custom model. 

A bit of good news on the co-occurrence, I was able to setup java path, had been messed up in my attempt to compile Scala. Someone had mentioned I had to use folder names with no space so I had moved java from under Program Files but forgot to make IntelliJ changes. However, app is now running but exiting with an error; can't find "com.finderbots.drivers.CooccurrenceDriver". I have it correctly set. I tried resetting it through ellipses it says "driver not acceptable".

Thanks.

**Comment by pferrel** [comment]
"Program Files" are you using Windows? 

This will not work on Windows! Some components work on Windows or with cygwin but IMO you are buying nothing but headaches trying to do this. Create a Virtual Machine and install Ubuntu Linux or Centos. Most Server code development is on some 'nix version (Mac is BSD Unix) so many developers do not take great care to make sure things run on Windows including me because I have no way to test it. For instance I know the Mahout Script for V0.10.0+ will not run on Windows.

**Comment by pferrel** [comment]
BTW this is not a good place to get support. Try an appropriate community mailing list or Google group.
